-- MySQL Script generated by MySQL Workbench
-- Wed Oct 30 15:29:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema terminal_automotriz
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS  terminal_automotriz;
USE  terminal_automotriz ;

-- -----------------------------------------------------
-- Table `mydb`.`Concensionaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS  `Concensionaria` (
  `cuitConcensionaria` VARCHAR(45) NOT NULL,
  `razonSocial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cuitConcensionaria`));


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedido` (
  `idPedido` INT NOT NULL,
  `fechaPedido` DATETIME NOT NULL,
  `cuitConcensionaria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Concensionaria1_idx` (`cuitConcensionaria` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Concensionaria1`
    FOREIGN KEY (`cuitConcensionaria`)
    REFERENCES `Concensionaria` (`cuitConcensionaria`));


-- -----------------------------------------------------
-- Table `mydb`.`ModeloVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ModeloVehiculo` (
  `idModeloVehiculo` INT NOT NULL,
  `modeloDescripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModeloVehiculo`));


-- -----------------------------------------------------
-- Table `mydb`.`LineaMontaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LineaMontaje` (
  `idLineaMontaje` INT NOT NULL,
  `modeloVehiculo` INT NOT NULL,
  PRIMARY KEY (`idLineaMontaje`),
  INDEX `fk_LineaMontaje_ModeloVehiculo1_idx` (`modeloVehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_LineaMontaje_ModeloVehiculo1`
    FOREIGN KEY (`modeloVehiculo`)
    REFERENCES `ModeloVehiculo` (`idModeloVehiculo`));


-- -----------------------------------------------------
-- Table `mydb`.`EstacionTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EstacionTrabajo` (
  `idEstacionTrabajo` INT NOT NULL,
  `lineaMontaje` INT NOT NULL,
  PRIMARY KEY (`idEstacionTrabajo`),
  INDEX `fk_EstacionTrabajo_LineaMontaje_idx` (`lineaMontaje` ASC) VISIBLE,
  CONSTRAINT `fk_EstacionTrabajo_LineaMontaje`
    FOREIGN KEY (`lineaMontaje`)
    REFERENCES `LineaMontaje` (`idLineaMontaje`));


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Detalle_Pedido` (
  `LineaMontaje_idLineaMontaje` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `cantPedido` INT NOT NULL,
  PRIMARY KEY (`LineaMontaje_idLineaMontaje`, `Pedido_idPedido`),
  INDEX `fk_LineaMontaje_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_LineaMontaje_has_Pedido_LineaMontaje1_idx` (`LineaMontaje_idLineaMontaje` ASC) VISIBLE,
  CONSTRAINT `fk_LineaMontaje_has_Pedido_LineaMontaje1`
    FOREIGN KEY (`LineaMontaje_idLineaMontaje`)
    REFERENCES `LineaMontaje` (`idLineaMontaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LineaMontaje_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Pedido` (`idPedido`));


-- -----------------------------------------------------
-- Table `mydb`.`Automovil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Automovil` (
  `chasis` INT NOT NULL,
  `fechaInicio` DATETIME NULL,
  `fechaFinalizacion` DATETIME NULL,
  `idLineaMontajeAsignada` INT NOT NULL,
  `idPedido` INT NOT NULL,
  PRIMARY KEY (`chasis`, `idLineaMontajeAsignada`, `idPedido`),
  INDEX `fk_Automovil_Detalle_Pedido1_idx` (`idLineaMontajeAsignada` ASC, `idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Automovil_Detalle_Pedido1`
    FOREIGN KEY (`idLineaMontajeAsignada` , `idPedido`)
    REFERENCES `Detalle_Pedido` (`LineaMontaje_idLineaMontaje` , `Pedido_idPedido`));


-- -----------------------------------------------------
-- Table `mydb`.`Provedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Provedor` (
  `cuitProvedor` VARCHAR(45) NOT NULL,
  `razonSocial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cuitProvedor`));


-- -----------------------------------------------------
-- Table `mydb`.`Insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insumo` (
  `idInsumo` INT NOT NULL,
  `descripcionInsumo` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`idInsumo`));


-- -----------------------------------------------------
-- Table `mydb`.`Insumo_Provedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Insumo_Provedor` (
  `Insumo_idInsumo` INT NOT NULL,
  `Provedor_cuitProvedor` VARCHAR(45) NOT NULL,
  INDEX `fk_Insumo_has_Provedor_Provedor1_idx` (`Provedor_cuitProvedor` ASC) VISIBLE,
  INDEX `fk_Insumo_has_Provedor_Insumo1_idx` (`Insumo_idInsumo` ASC) VISIBLE,
  PRIMARY KEY (`Insumo_idInsumo`, `Provedor_cuitProvedor`),
  CONSTRAINT `fk_Insumo_has_Provedor_Insumo1`
    FOREIGN KEY (`Insumo_idInsumo`)
    REFERENCES `Insumo` (`idInsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Insumo_has_Provedor_Provedor1`
    FOREIGN KEY (`Provedor_cuitProvedor`)
    REFERENCES `Provedor` (`cuitProvedor`));


-- -----------------------------------------------------
-- Table `mydb`.`Cantidad_Insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cantidad_Insumo` (
  `EstacionTrabajo_idEstacionTrabajo` INT NOT NULL,
  `Insumo_idInsumo` INT NOT NULL,
  `cantidadInsumo` INT NOT NULL,
  INDEX `fk_EstacionTrabajo_has_Insumo_Insumo1_idx` (`Insumo_idInsumo` ASC) VISIBLE,
  INDEX `fk_EstacionTrabajo_has_Insumo_EstacionTrabajo1_idx` (`EstacionTrabajo_idEstacionTrabajo` ASC) VISIBLE,
  PRIMARY KEY (`EstacionTrabajo_idEstacionTrabajo`, `Insumo_idInsumo`),
  CONSTRAINT `fk_EstacionTrabajo_has_Insumo_EstacionTrabajo1`
    FOREIGN KEY (`EstacionTrabajo_idEstacionTrabajo`)
    REFERENCES `EstacionTrabajo` (`idEstacionTrabajo`),
  CONSTRAINT `fk_EstacionTrabajo_has_Insumo_Insumo1`
    FOREIGN KEY (`Insumo_idInsumo`)
    REFERENCES `Insumo` (`idInsumo`));


-- -----------------------------------------------------
-- Table `mydb`.`Automovil_EstacionTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Automovil_EstacionTrabajo` (
  `Automovil_chasis` INT NOT NULL,
  `EstacionTrabajo_idEstacionTrabajo` INT NOT NULL,
  `fechaHoraIngreso` DATETIME NOT NULL,
  `fechaHoraEgreso` DATETIME ,
  INDEX `fk_Automovil_has_EstacionTrabajo_EstacionTrabajo1_idx` (`EstacionTrabajo_idEstacionTrabajo` ASC) VISIBLE,
  INDEX `fk_Automovil_has_EstacionTrabajo_Automovil1_idx` (`Automovil_chasis` ASC) VISIBLE,
  PRIMARY KEY (`EstacionTrabajo_idEstacionTrabajo`, `Automovil_chasis`),
  CONSTRAINT `fk_Automovil_has_EstacionTrabajo_Automovil1`
    FOREIGN KEY (`Automovil_chasis`)
    REFERENCES `Automovil` (`chasis`),
  CONSTRAINT `fk_Automovil_has_EstacionTrabajo_EstacionTrabajo1`
    FOREIGN KEY (`EstacionTrabajo_idEstacionTrabajo`)
    REFERENCES `EstacionTrabajo` (`idEstacionTrabajo`));

