-- MySQL Script generated by MySQL Workbench
-- Fri Sep  6 15:35:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Terminal Automotriz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Terminal Automotriz` ;
USE `Terminal Automotriz` ;

-- -----------------------------------------------------
-- Table `Terminal Automotriz`.`Concensionaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal Automotriz`.`Concensionaria` (
  `cuitConcensionaria` VARCHAR(45) NOT NULL,
  `razonSocial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cuitConcensionaria`));


-- -----------------------------------------------------
-- Table `Terminal Automotriz`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal Automotriz`.`Pedido` (
  `idPedido` INT NOT NULL,
  `fechaPedido` DATETIME NOT NULL,
  `fk_cuitConcensionaria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Concensionaria1_idx` (`fk_cuitConcensionaria` ASC) ,
  CONSTRAINT `fk_Pedido_Concensionaria1`
    FOREIGN KEY (`fk_cuitConcensionaria`)
    REFERENCES `Terminal Automotriz`.`Concensionaria` (`cuitConcensionaria`));


-- -----------------------------------------------------
-- Table `Terminal Automotriz`.`ModeloVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal Automotriz`.`ModeloVehiculo` (
  `idModeloVehiculo` INT NOT NULL,
  `modeloDescripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModeloVehiculo`));


-- -----------------------------------------------------
-- Table `Terminal Automotriz`.`LineaMontaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal Automotriz`.`LineaMontaje` (
  `idLineaMontaje` INT NOT NULL,
  `fk_modeloVehiculo` INT NOT NULL,
  PRIMARY KEY (`idLineaMontaje`),
  INDEX `fk_LineaMontaje_ModeloVehiculo1_idx` (`fk_modeloVehiculo` ASC) ,
  CONSTRAINT `fk_LineaMontaje_ModeloVehiculo1`
    FOREIGN KEY (`fk_modeloVehiculo`)
    REFERENCES `Terminal Automotriz`.`ModeloVehiculo` (`idModeloVehiculo`));


-- -----------------------------------------------------
-- Table `Terminal Automotriz`.`EstacionTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal Automotriz`.`EstacionTrabajo` (
  `idEstacionTrabajo` INT NOT NULL,
  `fk_lineaMontaje` INT NOT NULL,
  PRIMARY KEY (`idEstacionTrabajo`),
  INDEX `fk_EstacionTrabajo_LineaMontaje_idx` (`fk_lineaMontaje` ASC) ,
  CONSTRAINT `fk_EstacionTrabajo_LineaMontaje`
    FOREIGN KEY (`fk_lineaMontaje`)
    REFERENCES `Terminal Automotriz`.`LineaMontaje` (`idLineaMontaje`));


-- -----------------------------------------------------
-- Table `Terminal Automotriz`.`Detalle_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal Automotriz`.`Detalle_Pedido` (
  `ModeloVehiculo_idModeloVehiculo` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `cantPedido` INT NOT NULL,
  INDEX `fk_ModeloVehiculo_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) ,
  INDEX `fk_ModeloVehiculo_has_Pedido_ModeloVehiculo1_idx` (`ModeloVehiculo_idModeloVehiculo` ASC),
  PRIMARY KEY (`ModeloVehiculo_idModeloVehiculo`, `Pedido_idPedido`),
  CONSTRAINT `fk_ModeloVehiculo_has_Pedido_ModeloVehiculo1`
    FOREIGN KEY (`ModeloVehiculo_idModeloVehiculo`)
    REFERENCES `Terminal Automotriz`.`ModeloVehiculo` (`idModeloVehiculo`),
  CONSTRAINT `fk_ModeloVehiculo_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Terminal Automotriz`.`Pedido` (`idPedido`));


-- -----------------------------------------------------
-- Table `Terminal Automotriz`.`Automovil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal Automotriz`.`Automovil` (
  `chasis` VARCHAR(45) NOT NULL,
  `fk_modeloVehiculo` INT NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NULL,
  `fk_detallePedido_modeloVehiculo` INT NOT NULL,
  `fk_detalePedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`chasis`),
  INDEX `fk_Automovil_ModeloVehiculo1_idx` (`fk_modeloVehiculo` ASC) ,
  INDEX `fk_Automovil_DetallePedido1_idx` (`fk_detallePedido_modeloVehiculo` ASC, `fk_detalePedido_idPedido` ASC),
  CONSTRAINT `fk_Automovil_ModeloVehiculo1`
    FOREIGN KEY (`fk_modeloVehiculo`)
    REFERENCES `Terminal Automotriz`.`ModeloVehiculo` (`idModeloVehiculo`),
  CONSTRAINT `fk_Automovil_DetallePedido1`
    FOREIGN KEY (`fk_detallePedido_modeloVehiculo` , `fk_detalePedido_idPedido`)
    REFERENCES `Terminal Automotriz`.`Detalle_Pedido` (`ModeloVehiculo_idModeloVehiculo` , `Pedido_idPedido`));


-- -----------------------------------------------------
-- Table `Terminal Automotriz`.`Provedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal Automotriz`.`Provedor` (
  `cuitProvedor` VARCHAR(45) NOT NULL,
  `razonSocial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cuitProvedor`));


-- -----------------------------------------------------
-- Table `Terminal Automotriz`.`Insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal Automotriz`.`Insumo` (
  `idInsumo` INT NOT NULL,
  `descripcionInsumo` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`idInsumo`));


-- -----------------------------------------------------
-- Table `Terminal Automotriz`.`Insumo_Provedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal Automotriz`.`Insumo_Provedor` (
  `Insumo_idInsumo` INT NOT NULL,
  `Provedor_cuitProvedor` VARCHAR(45) NOT NULL,
  INDEX `fk_Insumo_has_Provedor_Provedor1_idx` (`Provedor_cuitProvedor` ASC) ,
  INDEX `fk_Insumo_has_Provedor_Insumo1_idx` (`Insumo_idInsumo` ASC) ,
  PRIMARY KEY (`Insumo_idInsumo`, `Provedor_cuitProvedor`),
  CONSTRAINT `fk_Insumo_has_Provedor_Insumo1`
    FOREIGN KEY (`Insumo_idInsumo`)
    REFERENCES `Terminal Automotriz`.`Insumo` (`idInsumo`),
  CONSTRAINT `fk_Insumo_has_Provedor_Provedor1`
    FOREIGN KEY (`Provedor_cuitProvedor`)
    REFERENCES `Terminal Automotriz`.`Provedor` (`cuitProvedor`));


-- -----------------------------------------------------
-- Table `Terminal Automotriz`.`Cantidad_Insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal Automotriz`.`Cantidad_Insumo` (
  `EstacionTrabajo_idEstacionTrabajo` INT NOT NULL,
  `Insumo_idInsumo` INT NOT NULL,
  `cantidadInsumo` INT NOT NULL,
  INDEX `fk_EstacionTrabajo_has_Insumo_Insumo1_idx` (`Insumo_idInsumo` ASC) ,
  INDEX `fk_EstacionTrabajo_has_Insumo_EstacionTrabajo1_idx` (`EstacionTrabajo_idEstacionTrabajo` ASC) ,
  PRIMARY KEY (`EstacionTrabajo_idEstacionTrabajo`, `Insumo_idInsumo`),
  CONSTRAINT `fk_EstacionTrabajo_has_Insumo_EstacionTrabajo1`
    FOREIGN KEY (`EstacionTrabajo_idEstacionTrabajo`)
    REFERENCES `Terminal Automotriz`.`EstacionTrabajo` (`idEstacionTrabajo`),
  CONSTRAINT `fk_EstacionTrabajo_has_Insumo_Insumo1`
    FOREIGN KEY (`Insumo_idInsumo`)
    REFERENCES `Terminal Automotriz`.`Insumo` (`idInsumo`));


-- -----------------------------------------------------
-- Table `Terminal Automotriz`.`Automovil_EstacionTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Terminal Automotriz`.`Automovil_EstacionTrabajo` (
  `Automovil_chasis` VARCHAR(45) NOT NULL,
  `EstacionTrabajo_idEstacionTrabajo` INT NOT NULL,
  `fechaHoraIngreso` DATETIME NOT NULL,
  `fechaHoraEgreso` DATETIME NOT NULL,
  INDEX `fk_Automovil_has_EstacionTrabajo_EstacionTrabajo1_idx` (`EstacionTrabajo_idEstacionTrabajo` ASC),
  INDEX `fk_Automovil_has_EstacionTrabajo_Automovil1_idx` (`Automovil_chasis` ASC) ,
  PRIMARY KEY (`EstacionTrabajo_idEstacionTrabajo`, `Automovil_chasis`),
  CONSTRAINT `fk_Automovil_has_EstacionTrabajo_Automovil1`
    FOREIGN KEY (`Automovil_chasis`)
    REFERENCES `Terminal Automotriz`.`Automovil` (`chasis`),
  CONSTRAINT `fk_Automovil_has_EstacionTrabajo_EstacionTrabajo1`
    FOREIGN KEY (`EstacionTrabajo_idEstacionTrabajo`)
    REFERENCES `Terminal Automotriz`.`EstacionTrabajo` (`idEstacionTrabajo`));



/************************************************************************************************************/
-- TABLAS UTILIZADAS POR LOS TRIGGERS
/************************************************************************----------------------------------**/
-- INSUMO
/*


create table reg_insumo_agregado
(
	idInsumo int,
    descripcionInsumo varchar(45),
    precio double,
    fechaIngreso datetime
);
create table reg_insumo_actualizado
(
    descripcionInsumo_vieja varchar(45),
    descripcionInsumo_nueva varchar(45),
    precio_viejo double,
    precio_nuevo double,
    usuario varchar(45),
    fechaActualizacion datetime
);
create table reg_insumo_eliminado
(
	idInsumo int,
    descripcionInsumo varchar(45),
    precio double,
	fechaEliminacion datetime

);


-- CONCENSIONARIA
create table reg_concensionaria_agregado
(
	cuitConcensionaria varchar(45),
    razonSocial varchar(45),
    fechaIngreso datetime
);
create table reg_concensionaria_actualizada
(
    razonSocial_vieja varchar(45),
	razonSocial_nueva varchar(45),
    usuario varchar(45),
    fechaActualizacion datetime
);
create table reg_concensionaria_eliminado
(
	cuitConcensionaria varchar(45),
    razonSocial varchar(45),
	fechaEliminacion datetime

);


-- PEDIDO
create table reg_pedido_agregado
(
	idPedido int,
    fechaPedido datetime,
    descripcionPedido varchar(45),
    cuitConcensionaria varchar(45),
    fechaIngreso datetime
);
create table reg_pedido_actualizada
(
	fechaPedido_vieja datetime,
    fechaPedido_nueva datetime,
    descripcionPedido_vieja varchar(45),
	descripcionPedido_nueva varchar(45),
    cuitConcensionaria_vieja varchar(45),
    cuitConcensionaria_nueva varchar(45),
    usuario varchar(45),
    fechaActualizacion datetime
);
create table reg_pedido_eliminado
(
	idPedido int,
	fechaPedido datetime,
    descripcionPedido varchar(45),
    cuitConcensionaria varchar(45),
	fechaEliminacion datetime
);


*/